### ISSUE TITLE
Figure out why rear strafe motor doesn't turn.

### ISSUE THREAD

**Issue by mcolinj** [FRC1076/2020-wapur#3]
It appears that the number 4 motor controller is wired to the motor, but you'll need to test it out, and involve electrical.   Consider what could be wrong..

We might be driving the motor with the wrong value.
We might have the CAN ID set improperly in the software.
The motor controller might not have the the correct CAN ID.
The controller might not be connected to the motor.
The controller might be broken.
The motor might be broken.

Attack these one at a time to figure out what is going on.

**Comment by VeeBallbach** [comment]
Solved, the controller itself wasn't working.
