### ISSUE TITLE
Find out what the motor safety incantation is, and put it into the robot code

### ISSUE THREAD

**Issue by mcolinj** [FRC1076/2020-wapur#4]
A bug in the robot code was preventing the motors from getting updated every cycle.

This should not cause a safety issue if the robot is configured to shut down the motors if they do not receive an update every cycle.

However, this code doesn't have that in it.

Look around in other comp bot code, look at some readthedocs documentation, maybe do a google search for pyfrc motor safety or something.

We need this in our robot.

**Comment by Ofek-Shani** [comment]
I did it. I saved the world.
